### ISSUE TITLE
Drop .gen package

### ISSUE THREAD

**Issue by kolovos** [York-and-Maastricht-Data-Science-Group/vaultage#10]
The .gen package doesn't seem to be necessary so I'd suggest dropping it and generating both the base classes and the stubs under the same package (but under different source folders - as we currently do)

https://github.com/York-and-Maastricht-Data-Science-Group/vaultage/blob/83d1a798f42a3db7436827be6fb2a78bc2d5e180/org.vaultage.generator/generator/Vaultage.egx#L10

**Comment by alfonsodelavega** [comment]
Once this change is done, those classes that end up in the `src-gen` source folder, should we commit them so that the projects compile just by importing them?

Right now, we are ignoring the `gen` folder (at least in pollen). I did it to avoid polluting commits with a lot of changes due to generator evolution.

**Comment by kolovos** [comment]
> Once this change is done, those classes that end up in the `src-gen` source folder, should we commit them so that the projects compile just by importing them?

I'd gitignore generated code.
